FROM node:8.6

# dumb-init acts as PID 1 and immediately spawns your command as a child process, taking care to properly handle and forward signals as they are received.
RUN wget https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64.deb
RUN dpkg -i dumb-init_*.deb

# Set Home env, this is where our app is going to live
ENV HOME=/usr/app

# Change directory so that our commands run inside this new directory
WORKDIR $HOME/src

# DISABLED
# Copy the dependencies description and set permissions to app
# COPY package.json $HOME/src
# RUN chown -R app:app $HOME/*

# DISABLED
# User for any RUN, CMD and ENTRYPOINT command
# Warning: When the user does doesn’t have a primary group then the image (or the next instructions) will be run with the root group.
# USER app

# Install and Cache npm packages
RUN npm install

# DISABLED
# Install npm global packages
# RUN npm install -g gulp

# DISABLED
# Expose the port the app runs in
EXPOSE 3000

# DISABLED
# Serve the app
# CMD ["gulp", "dev"]

ENTRYPOINT ["/usr/bin/dumb-init", "--", "./docker-entrypoint-dev.sh"]
